/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 15 20:09:07 GMT 2018
 */

package com.github.cseppento.gradle.evosuite.testprojects.simple;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut;
import java.util.SortedSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SimpleObjectSut_ESTest extends SimpleObjectSut_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(971L);
      simpleObjectSut0.check();
      assertEquals(971L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(267L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(779L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 779 is not a divisor of 267
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(971L);
      simpleObjectSut0.guessDivisor(971L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(971L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 971 is already added as a divisor of 971
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      // Undeclared exception!
      try { 
        simpleObjectSut0.guessDivisor(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid divisor: 0
         //
         verifyException("com.github.cseppento.gradle.evosuite.testprojects.simple.SimpleObjectSut", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(0L);
      simpleObjectSut0.guessDivisor(1L);
      simpleObjectSut0.check();
      assertEquals(0L, simpleObjectSut0.getValue());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-1196L));
      SortedSet<Long> sortedSet0 = simpleObjectSut0.getDivisors();
      assertFalse(sortedSet0.contains((-1196L)));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut(2482L);
      String string0 = simpleObjectSut0.toString();
      assertEquals("SimpleObjectSut of 2482 with divisors []", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SimpleObjectSut simpleObjectSut0 = new SimpleObjectSut((-3589L));
      long long0 = simpleObjectSut0.getValue();
      assertEquals(3589L, long0);
  }
}
